{"Url": "https://www.imdb.com/title/tt6161168/?ref_=ttls_li_i", "Page_Title": "Red Dead Redemption II (Video Game 2018) - IMDb", "Number of Critics": "18", "Age Rating": "M", "Release Year": "2018"}
{"Url": "https://www.imdb.com/title/tt6161168/?ref_=ttls_li_tt", "Page_Title": "Red Dead Redemption II (Video Game 2018) - IMDb", "Number of Critics": "18", "Age Rating": "M", "Release Year": "2018"}
{"Url": "https://www.imdb.com/title/tt2140553/?ref_=ttls_li_i", "Page_Title": "The Last of Us (Video Game 2013) - IMDb", "Number of Critics": "59", "Age Rating": "M", "Release Year": "2013"}
{"Url": "https://www.imdb.com/title/tt2140553/?ref_=ttls_li_tt", "Page_Title": "The Last of Us (Video Game 2013) - IMDb", "Number of Critics": "59", "Age Rating": "M", "Release Year": "2013"}
{"Url": "https://www.imdb.com/title/tt1479962/?ref_=ttls_li_i", "Page_Title": "Red Dead Redemption (Video Game 2010) - IMDb", "Number of Critics": "13", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt1479962/?ref_=ttls_li_tt", "Page_Title": "Red Dead Redemption (Video Game 2010) - IMDb", "Number of Critics": "13", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt0486673/?ref_=ttls_li_i", "Page_Title": "Shadow of the Colossus (Video Game 2005) - IMDb", "Number of Critics": "6", "Age Rating": "T", "Release Year": "2005"}
{"Url": "https://www.imdb.com/title/tt0486673/?ref_=ttls_li_tt", "Page_Title": "Shadow of the Colossus (Video Game 2005) - IMDb", "Number of Critics": "6", "Age Rating": "T", "Release Year": "2005"}
{"Url": "https://www.imdb.com/title/tt1814884/?ref_=ttls_li_i", "Page_Title": "The Elder Scrolls V: Skyrim (Video Game 2011) - IMDb", "Number of Critics": "15", "Age Rating": "M", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt1814884/?ref_=ttls_li_tt", "Page_Title": "The Elder Scrolls V: Skyrim (Video Game 2011) - IMDb", "Number of Critics": "15", "Age Rating": "M", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt4044024/?ref_=ttls_li_i", "Page_Title": "Horizon Zero Dawn (Video Game 2017) - IMDb", "Number of Critics": "8", "Age Rating": "T", "Release Year": "2017"}
{"Url": "https://www.imdb.com/title/tt4044024/?ref_=ttls_li_tt", "Page_Title": "Horizon Zero Dawn (Video Game 2017) - IMDb", "Number of Critics": "8", "Age Rating": "T", "Release Year": "2017"}
{"Url": "https://www.imdb.com/title/tt0282975/?ref_=ttls_li_i", "Page_Title": "Silent Hill 2 (Video Game 2001) - IMDb", "Number of Critics": "6", "Age Rating": "M", "Release Year": "2001"}
{"Url": "https://www.imdb.com/title/tt0282975/?ref_=ttls_li_tt", "Page_Title": "Silent Hill 2 (Video Game 2001) - IMDb", "Number of Critics": "6", "Age Rating": "M", "Release Year": "2001"}
{"Url": "https://www.imdb.com/title/tt3944082/?ref_=ttls_li_i", "Page_Title": "Persona 5 (Video Game 2016) - IMDb", "Number of Critics": "8", "Age Rating": "M", "Release Year": "2016"}
{"Url": "https://www.imdb.com/title/tt3944082/?ref_=ttls_li_tt", "Page_Title": "Persona 5 (Video Game 2016) - IMDb", "Number of Critics": "8", "Age Rating": "M", "Release Year": "2016"}
{"Url": "https://www.imdb.com/title/tt11177022/?ref_=ttls_li_i", "Page_Title": "Disco Elysium (Video Game 2019) - IMDb", "Number of Critics": "1", "Age Rating": "M", "Release Year": "2019"}
{"Url": "https://www.imdb.com/title/tt11177022/?ref_=ttls_li_tt", "Page_Title": "Disco Elysium (Video Game 2019) - IMDb", "Number of Critics": "1", "Age Rating": "M", "Release Year": "2019"}
{"Url": "https://www.imdb.com/title/tt5838588/?ref_=ttls_li_i", "Page_Title": "God of War (Video Game 2018) - IMDb", "Number of Critics": "11", "Age Rating": "M", "Release Year": "2018"}
{"Url": "https://www.imdb.com/title/tt5838588/?ref_=ttls_li_tt", "Page_Title": "God of War (Video Game 2018) - IMDb", "Number of Critics": "11", "Age Rating": "M", "Release Year": "2018"}
{"Url": "https://www.imdb.com/title/tt3003738/?ref_=ttls_li_i", "Page_Title": "Persona 4 Golden (Video Game 2012) - IMDb", "Number of Critics": "2", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt3003738/?ref_=ttls_li_tt", "Page_Title": "Persona 4 Golden (Video Game 2012) - IMDb", "Number of Critics": "2", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt0210613/?ref_=ttls_li_i", "Page_Title": "Chrono Trigger (Video Game 1995) - IMDb", "Number of Critics": "169", "Age Rating": "E", "Release Year": "1995"}
{"Url": "https://www.imdb.com/title/tt0210613/?ref_=ttls_li_tt", "Page_Title": "Chrono Trigger (Video Game 1995) - IMDb", "Number of Critics": "169", "Age Rating": "E", "Release Year": "1995"}
{"Url": "https://www.imdb.com/title/tt1540125/?ref_=ttls_li_i", "Page_Title": "Mass Effect 2 (Video Game 2010) - IMDb", "Number of Critics": "4", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt1540125/?ref_=ttls_li_tt", "Page_Title": "Mass Effect 2 (Video Game 2010) - IMDb", "Number of Critics": "4", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt1821474/?ref_=ttls_li_i", "Page_Title": "Journey (Video Game 2012) - IMDb", "Number of Critics": "21", "Age Rating": "E", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt1821474/?ref_=ttls_li_tt", "Page_Title": "Journey (Video Game 2012) - IMDb", "Number of Critics": "21", "Age Rating": "E", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt4485128/?ref_=ttls_li_i", "Page_Title": "What Remains of Edith Finch (Video Game 2017) - IMDb", "Number of Critics": "7", "Age Rating": "T", "Release Year": "2017"}
{"Url": "https://www.imdb.com/title/tt4485128/?ref_=ttls_li_tt", "Page_Title": "What Remains of Edith Finch (Video Game 2017) - IMDb", "Number of Critics": "7", "Age Rating": "T", "Release Year": "2017"}
{"Url": "https://www.imdb.com/title/tt2103188/?ref_=ttls_li_i", "Page_Title": "Grand Theft Auto V (Video Game 2013) - IMDb", "Number of Critics": "39", "Age Rating": "M", "Release Year": "2013"}
{"Url": "https://www.imdb.com/title/tt2103188/?ref_=ttls_li_tt", "Page_Title": "Grand Theft Auto V (Video Game 2013) - IMDb", "Number of Critics": "39", "Age Rating": "M", "Release Year": "2013"}
{"Url": "https://www.imdb.com/title/tt2006890/?ref_=ttls_li_i", "Page_Title": "The Walking Dead: A Telltale Game Series (Video Game 2012) - IMDb", "Number of Critics": "21", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt2006890/?ref_=ttls_li_tt", "Page_Title": "The Walking Dead: A Telltale Game Series (Video Game 2012) - IMDb", "Number of Critics": "21", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt1349460/?ref_=ttls_li_i", "Page_Title": "Uncharted 2: Among Thieves (Video Game 2009) - IMDb", "Number of Critics": "4", "Age Rating": "T", "Release Year": "2009"}
{"Url": "https://www.imdb.com/title/tt1349460/?ref_=ttls_li_tt", "Page_Title": "Uncharted 2: Among Thieves (Video Game 2009) - IMDb", "Number of Critics": "4", "Age Rating": "T", "Release Year": "2009"}
{"Url": "https://www.imdb.com/title/tt2993508/?ref_=ttls_li_i", "Page_Title": "The Witcher 3: Wild Hunt (Video Game 2015) - IMDb", "Number of Critics": "15", "Age Rating": "M", "Release Year": "2015"}
{"Url": "https://www.imdb.com/title/tt2993508/?ref_=ttls_li_tt", "Page_Title": "The Witcher 3: Wild Hunt (Video Game 2015) - IMDb", "Number of Critics": "15", "Age Rating": "M", "Release Year": "2015"}
{"Url": "https://www.imdb.com/title/tt2233084/?ref_=ttls_li_i", "Page_Title": "Spec Ops: The Line (Video Game 2012) - IMDb", "Number of Critics": "3", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt2233084/?ref_=ttls_li_tt", "Page_Title": "Spec Ops: The Line (Video Game 2012) - IMDb", "Number of Critics": "3", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt1094581/?ref_=ttls_li_i", "Page_Title": "BioShock (Video Game 2007) - IMDb", "Number of Critics": "15", "Age Rating": "M", "Release Year": "2007"}
{"Url": "https://www.imdb.com/title/tt1094581/?ref_=ttls_li_tt", "Page_Title": "BioShock (Video Game 2007) - IMDb", "Number of Critics": "15", "Age Rating": "M", "Release Year": "2007"}
{"Url": "https://www.imdb.com/title/tt1568322/?ref_=ttls_li_i", "Page_Title": "Batman: Arkham City (Video Game 2011) - IMDb", "Number of Critics": "12", "Age Rating": "T", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt1568322/?ref_=ttls_li_tt", "Page_Title": "Batman: Arkham City (Video Game 2011) - IMDb", "Number of Critics": "12", "Age Rating": "T", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt1706601/?ref_=ttls_li_i", "Page_Title": "Fallout: New Vegas (Video Game 2010) - IMDb", "Number of Critics": "3", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt1706601/?ref_=ttls_li_tt", "Page_Title": "Fallout: New Vegas (Video Game 2010) - IMDb", "Number of Critics": "3", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt0244661/?ref_=ttls_li_i", "Page_Title": "Monkey Island 2: LeChuck's Revenge (Video Game 1991) - IMDb", "Number of Critics": "4", "Age Rating": "No Rating", "Release Year": "1991"}
{"Url": "https://www.imdb.com/title/tt0244661/?ref_=ttls_li_tt", "Page_Title": "Monkey Island 2: LeChuck's Revenge (Video Game 1991) - IMDb", "Number of Critics": "4", "Age Rating": "No Rating", "Release Year": "1991"}
{"Url": "https://www.imdb.com/title/tt0802999/?ref_=ttls_li_i", "Page_Title": "Grand Theft Auto IV (Video Game 2008) - IMDb", "Number of Critics": "13", "Age Rating": "M", "Release Year": "2008"}
{"Url": "https://www.imdb.com/title/tt0802999/?ref_=ttls_li_tt", "Page_Title": "Grand Theft Auto IV (Video Game 2008) - IMDb", "Number of Critics": "13", "Age Rating": "M", "Release Year": "2008"}
{"Url": "https://www.imdb.com/title/tt7651352/?ref_=ttls_li_i", "Page_Title": "Ghost of Tsushima (Video Game 2020) - IMDb", "Number of Critics": "8", "Age Rating": "M", "Release Year": "2020"}
{"Url": "https://www.imdb.com/title/tt7651352/?ref_=ttls_li_tt", "Page_Title": "Ghost of Tsushima (Video Game 2020) - IMDb", "Number of Critics": "8", "Age Rating": "M", "Release Year": "2020"}
{"Url": "https://www.imdb.com/title/tt3334704/?ref_=ttls_li_i", "Page_Title": "Uncharted 4: A Thief's End (Video Game 2016) - IMDb", "Number of Critics": "20", "Age Rating": "T", "Release Year": "2016"}
{"Url": "https://www.imdb.com/title/tt3334704/?ref_=ttls_li_tt", "Page_Title": "Uncharted 4: A Thief's End (Video Game 2016) - IMDb", "Number of Critics": "20", "Age Rating": "T", "Release Year": "2016"}
{"Url": "https://www.imdb.com/title/tt1764429/?ref_=ttls_li_i", "Page_Title": "L.A. Noire (Video Game 2011) - IMDb", "Number of Critics": "21", "Age Rating": "M", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt1764429/?ref_=ttls_li_tt", "Page_Title": "L.A. Noire (Video Game 2011) - IMDb", "Number of Critics": "21", "Age Rating": "M", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt3814634/?ref_=ttls_li_i", "Page_Title": "Bloodborne (Video Game 2015) - IMDb", "Number of Critics": "6", "Age Rating": "M", "Release Year": "2015"}
{"Url": "https://www.imdb.com/title/tt3814634/?ref_=ttls_li_tt", "Page_Title": "Bloodborne (Video Game 2015) - IMDb", "Number of Critics": "6", "Age Rating": "M", "Release Year": "2015"}
{"Url": "https://www.imdb.com/title/tt6155214/?ref_=ttls_li_i", "Page_Title": "Danganronpa 2: Goodbye Despair (Video Game 2012) - IMDb", "Number of Critics": "1", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt6155214/?ref_=ttls_li_tt", "Page_Title": "Danganronpa 2: Goodbye Despair (Video Game 2012) - IMDb", "Number of Critics": "1", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt1606610/?ref_=ttls_li_i", "Page_Title": "Heavy Rain (Video Game 2010) - IMDb", "Number of Critics": "6", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt1606610/?ref_=ttls_li_tt", "Page_Title": "Heavy Rain (Video Game 2010) - IMDb", "Number of Critics": "6", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt0462271/?ref_=ttls_li_i", "Page_Title": "The Elder Scrolls IV: Oblivion (Video Game 2006) - IMDb", "Number of Critics": "3", "Age Rating": "T", "Release Year": "2006"}
{"Url": "https://www.imdb.com/title/tt0462271/?ref_=ttls_li_tt", "Page_Title": "The Elder Scrolls IV: Oblivion (Video Game 2006) - IMDb", "Number of Critics": "3", "Age Rating": "T", "Release Year": "2006"}
{"Url": "https://www.imdb.com/title/tt6298000/?ref_=ttls_li_i", "Page_Title": "The Last of Us: Part II (Video Game 2020) - IMDb", "Number of Critics": "15", "Age Rating": "M", "Release Year": "2020"}
{"Url": "https://www.imdb.com/title/tt6298000/?ref_=ttls_li_tt", "Page_Title": "The Last of Us: Part II (Video Game 2020) - IMDb", "Number of Critics": "15", "Age Rating": "M", "Release Year": "2020"}
{"Url": "https://www.imdb.com/title/tt3110552/?ref_=ttls_li_i", "Page_Title": "Hotline Miami (Video Game 2012) - IMDb", "Number of Critics": "12", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt3110552/?ref_=ttls_li_tt", "Page_Title": "Hotline Miami (Video Game 2012) - IMDb", "Number of Critics": "12", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt1800763/?ref_=ttls_li_i", "Page_Title": "Uncharted 3: Drake's Deception (Video Game 2011) - IMDb", "Number of Critics": "66", "Age Rating": "T", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt1800763/?ref_=ttls_li_tt", "Page_Title": "Uncharted 3: Drake's Deception (Video Game 2011) - IMDb", "Number of Critics": "66", "Age Rating": "T", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt5238626/?ref_=ttls_li_i", "Page_Title": "NieR: Automata (Video Game 2017) - IMDb", "Number of Critics": "8", "Age Rating": "M", "Release Year": "2017"}
{"Url": "https://www.imdb.com/title/tt5238626/?ref_=ttls_li_tt", "Page_Title": "NieR: Automata (Video Game 2017) - IMDb", "Number of Critics": "8", "Age Rating": "M", "Release Year": "2017"}
{"Url": "https://www.imdb.com/title/tt1697062/?ref_=ttls_li_i", "Page_Title": "Dead Space 2 (Video Game 2011) - IMDb", "Number of Critics": "7", "Age Rating": "M", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt1697062/?ref_=ttls_li_tt", "Page_Title": "Dead Space 2 (Video Game 2011) - IMDb", "Number of Critics": "7", "Age Rating": "M", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt1712064/?ref_=ttls_li_i", "Page_Title": "BioShock Infinite (Video Game 2013) - IMDb", "Number of Critics": "22", "Age Rating": "M", "Release Year": "2013"}
{"Url": "https://www.imdb.com/title/tt1712064/?ref_=ttls_li_tt", "Page_Title": "BioShock Infinite (Video Game 2013) - IMDb", "Number of Critics": "22", "Age Rating": "M", "Release Year": "2013"}
{"Url": "https://www.imdb.com/title/tt0208155/?ref_=ttls_li_i", "Page_Title": "Final Fantasy VII (Video Game 1997) - IMDb", "Number of Critics": "7", "Age Rating": "T", "Release Year": "1997"}
{"Url": "https://www.imdb.com/title/tt0208155/?ref_=ttls_li_tt", "Page_Title": "Final Fantasy VII (Video Game 1997) - IMDb", "Number of Critics": "7", "Age Rating": "T", "Release Year": "1997"}
{"Url": "https://www.imdb.com/title/tt1667847/?ref_=ttls_li_i", "Page_Title": "NieR (Video Game 2010) - IMDb", "Number of Critics": "0", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt1667847/?ref_=ttls_li_tt", "Page_Title": "NieR (Video Game 2010) - IMDb", "Number of Critics": "0", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt3130160/?ref_=ttls_li_i", "Page_Title": "Brothers: A Tale of Two Sons (Video Game 2013) - IMDb", "Number of Critics": "7", "Age Rating": "T", "Release Year": "2013"}
{"Url": "https://www.imdb.com/title/tt3130160/?ref_=ttls_li_tt", "Page_Title": "Brothers: A Tale of Two Sons (Video Game 2013) - IMDb", "Number of Critics": "7", "Age Rating": "T", "Release Year": "2013"}
{"Url": "https://www.imdb.com/title/tt3528758/?ref_=ttls_li_i", "Page_Title": "Danganronpa: Trigger Happy Havoc (Video Game 2010) - IMDb", "Number of Critics": "2", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt3528758/?ref_=ttls_li_tt", "Page_Title": "Danganronpa: Trigger Happy Havoc (Video Game 2010) - IMDb", "Number of Critics": "2", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt2040279/?ref_=ttls_li_i", "Page_Title": "Bastion (Video Game 2011) - IMDb", "Number of Critics": "0", "Age Rating": "No Rating", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt2040279/?ref_=ttls_li_tt", "Page_Title": "Bastion (Video Game 2011) - IMDb", "Number of Critics": "0", "Age Rating": "No Rating", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt1310502/?ref_=ttls_li_i", "Page_Title": "Fable II (Video Game 2008) - IMDb", "Number of Critics": "3", "Age Rating": "M", "Release Year": "2008"}
{"Url": "https://www.imdb.com/title/tt1310502/?ref_=ttls_li_tt", "Page_Title": "Fable II (Video Game 2008) - IMDb", "Number of Critics": "3", "Age Rating": "M", "Release Year": "2008"}
{"Url": "https://www.imdb.com/title/tt1541718/?ref_=ttls_li_i", "Page_Title": "Dragon Age: Origins (Video Game 2009) - IMDb", "Number of Critics": "4", "Age Rating": "M", "Release Year": "2009"}
{"Url": "https://www.imdb.com/title/tt1541718/?ref_=ttls_li_tt", "Page_Title": "Dragon Age: Origins (Video Game 2009) - IMDb", "Number of Critics": "4", "Age Rating": "M", "Release Year": "2009"}
{"Url": "https://www.imdb.com/title/tt1961357/?ref_=ttls_li_i", "Page_Title": "inFamous 2 (Video Game 2011) - IMDb", "Number of Critics": "1", "Age Rating": "T", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt1961357/?ref_=ttls_li_tt", "Page_Title": "inFamous 2 (Video Game 2011) - IMDb", "Number of Critics": "1", "Age Rating": "T", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt0374692/?ref_=ttls_li_i", "Page_Title": "Half-Life 2 (Video Game 2004) - IMDb", "Number of Critics": "11", "Age Rating": "M", "Release Year": "2004"}
{"Url": "https://www.imdb.com/title/tt0374692/?ref_=ttls_li_tt", "Page_Title": "Half-Life 2 (Video Game 2004) - IMDb", "Number of Critics": "11", "Age Rating": "M", "Release Year": "2004"}
{"Url": "https://www.imdb.com/title/tt1663344/?ref_=ttls_li_i", "Page_Title": "LittleBigPlanet 2 (Video Game 2011) - IMDb", "Number of Critics": "0", "Age Rating": "E", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt1663344/?ref_=ttls_li_tt", "Page_Title": "LittleBigPlanet 2 (Video Game 2011) - IMDb", "Number of Critics": "0", "Age Rating": "E", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt0323974/?ref_=ttls_li_i", "Page_Title": "Silent Hill 3 (Video Game 2003) - IMDb", "Number of Critics": "2", "Age Rating": "M", "Release Year": "2003"}
{"Url": "https://www.imdb.com/title/tt0323974/?ref_=ttls_li_tt", "Page_Title": "Silent Hill 3 (Video Game 2003) - IMDb", "Number of Critics": "2", "Age Rating": "M", "Release Year": "2003"}
{"Url": "https://www.imdb.com/title/tt10562854/?ref_=ttls_li_i", "Page_Title": "Elden Ring (Video Game 2022) - IMDb", "Number of Critics": "15", "Age Rating": "M", "Release Year": "2022"}
{"Url": "https://www.imdb.com/title/tt10562854/?ref_=ttls_li_tt", "Page_Title": "Elden Ring (Video Game 2022) - IMDb", "Number of Critics": "15", "Age Rating": "M", "Release Year": "2022"}
{"Url": "https://www.imdb.com/title/tt0203441/?ref_=ttls_li_i", "Page_Title": "Day of the Tentacle (Video Game 1993) - IMDb", "Number of Critics": "2", "Age Rating": "E", "Release Year": "1993"}
{"Url": "https://www.imdb.com/title/tt0203441/?ref_=ttls_li_tt", "Page_Title": "Day of the Tentacle (Video Game 1993) - IMDb", "Number of Critics": "2", "Age Rating": "E", "Release Year": "1993"}
{"Url": "https://www.imdb.com/title/tt0397042/?ref_=ttls_li_i", "Page_Title": "Resident Evil 4 (Video Game 2005) - IMDb", "Number of Critics": "11", "Age Rating": "M", "Release Year": "2005"}
{"Url": "https://www.imdb.com/title/tt0397042/?ref_=ttls_li_tt", "Page_Title": "Resident Evil 4 (Video Game 2005) - IMDb", "Number of Critics": "11", "Age Rating": "M", "Release Year": "2005"}
{"Url": "https://www.imdb.com/title/tt1201133/?ref_=ttls_li_i", "Page_Title": "Assassin's Creed II (Video Game 2009) - IMDb", "Number of Critics": "2", "Age Rating": "M", "Release Year": "2009"}
{"Url": "https://www.imdb.com/title/tt1201133/?ref_=ttls_li_tt", "Page_Title": "Assassin's Creed II (Video Game 2009) - IMDb", "Number of Critics": "2", "Age Rating": "M", "Release Year": "2009"}
{"Url": "https://www.imdb.com/title/tt0187405/?ref_=ttls_li_i", "Page_Title": "Planescape: Torment (Video Game 1999) - IMDb", "Number of Critics": "1", "Age Rating": "T", "Release Year": "1999"}
{"Url": "https://www.imdb.com/title/tt0187405/?ref_=ttls_li_tt", "Page_Title": "Planescape: Torment (Video Game 1999) - IMDb", "Number of Critics": "1", "Age Rating": "T", "Release Year": "1999"}
{"Url": "https://www.imdb.com/title/tt1648163/?ref_=ttls_li_i", "Page_Title": "Portal 2 (Video Game 2011) - IMDb", "Number of Critics": "16", "Age Rating": "E10+", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt1648163/?ref_=ttls_li_tt", "Page_Title": "Portal 2 (Video Game 2011) - IMDb", "Number of Critics": "16", "Age Rating": "E10+", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt1199781/?ref_=ttls_li_i", "Page_Title": "God of War III (Video Game 2010) - IMDb", "Number of Critics": "1", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt1199781/?ref_=ttls_li_tt", "Page_Title": "God of War III (Video Game 2010) - IMDb", "Number of Critics": "1", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt1756534/?ref_=ttls_li_i", "Page_Title": "God of War: Ghost of Sparta (Video Game 2010) - IMDb", "Number of Critics": "13", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt1756534/?ref_=ttls_li_tt", "Page_Title": "God of War: Ghost of Sparta (Video Game 2010) - IMDb", "Number of Critics": "13", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt2395486/?ref_=ttls_li_i", "Page_Title": "Machinarium (Video Game 2009) - IMDb", "Number of Critics": "0", "Age Rating": "No Rating", "Release Year": "2009"}
{"Url": "https://www.imdb.com/title/tt2395486/?ref_=ttls_li_tt", "Page_Title": "Machinarium (Video Game 2009) - IMDb", "Number of Critics": "0", "Age Rating": "No Rating", "Release Year": "2009"}
{"Url": "https://www.imdb.com/title/tt1073664/?ref_=ttls_li_i", "Page_Title": "Fallout 3 (Video Game 2008) - IMDb", "Number of Critics": "5", "Age Rating": "M", "Release Year": "2008"}
{"Url": "https://www.imdb.com/title/tt1073664/?ref_=ttls_li_tt", "Page_Title": "Fallout 3 (Video Game 2008) - IMDb", "Number of Critics": "5", "Age Rating": "M", "Release Year": "2008"}
{"Url": "https://www.imdb.com/title/tt0846694/?ref_=ttls_li_i", "Page_Title": "God of War II (Video Game 2007) - IMDb", "Number of Critics": "3", "Age Rating": "M", "Release Year": "2007"}
{"Url": "https://www.imdb.com/title/tt0846694/?ref_=ttls_li_tt", "Page_Title": "God of War II (Video Game 2007) - IMDb", "Number of Critics": "3", "Age Rating": "M", "Release Year": "2007"}
{"Url": "https://www.imdb.com/title/tt3253986/?ref_=ttls_li_i", "Page_Title": "The Legend of Zelda: Breath of the Wild (Video Game 2017) - IMDb", "Number of Critics": "21", "Age Rating": "E10+", "Release Year": "2017"}
{"Url": "https://www.imdb.com/title/tt3253986/?ref_=ttls_li_tt", "Page_Title": "The Legend of Zelda: Breath of the Wild (Video Game 2017) - IMDb", "Number of Critics": "21", "Age Rating": "E10+", "Release Year": "2017"}
{"Url": "https://www.imdb.com/title/tt0249008/?ref_=ttls_li_i", "Page_Title": "Metal Gear Solid 2: Sons of Liberty (Video Game 2001) - IMDb", "Number of Critics": "7", "Age Rating": "M", "Release Year": "2001"}
{"Url": "https://www.imdb.com/title/tt0249008/?ref_=ttls_li_tt", "Page_Title": "Metal Gear Solid 2: Sons of Liberty (Video Game 2001) - IMDb", "Number of Critics": "7", "Age Rating": "M", "Release Year": "2001"}
{"Url": "https://www.imdb.com/title/tt1282022/?ref_=ttls_li_i", "Page_Title": "Batman: Arkham Asylum (Video Game 2009) - IMDb", "Number of Critics": "12", "Age Rating": "T", "Release Year": "2009"}
{"Url": "https://www.imdb.com/title/tt1282022/?ref_=ttls_li_tt", "Page_Title": "Batman: Arkham Asylum (Video Game 2009) - IMDb", "Number of Critics": "12", "Age Rating": "T", "Release Year": "2009"}
{"Url": "https://www.imdb.com/title/tt4375662/?ref_=ttls_li_i", "Page_Title": "Life Is Strange (Video Game 2015) - IMDb", "Number of Critics": "8", "Age Rating": "M", "Release Year": "2015"}
{"Url": "https://www.imdb.com/title/tt4375662/?ref_=ttls_li_tt", "Page_Title": "Life Is Strange (Video Game 2015) - IMDb", "Number of Critics": "8", "Age Rating": "M", "Release Year": "2015"}
{"Url": "https://www.imdb.com/title/tt6057416/?ref_=ttls_li_i", "Page_Title": "Final Fantasy VII Remake (Video Game 2020) - IMDb", "Number of Critics": "12", "Age Rating": "T", "Release Year": "2020"}
{"Url": "https://www.imdb.com/title/tt6057416/?ref_=ttls_li_tt", "Page_Title": "Final Fantasy VII Remake (Video Game 2020) - IMDb", "Number of Critics": "12", "Age Rating": "T", "Release Year": "2020"}
{"Url": "https://www.imdb.com/title/tt0208155/", "Page_Title": "Final Fantasy VII (Video Game 1997) - IMDb", "Number of Critics": "7", "Age Rating": "T", "Release Year": "1997"}
{"Url": "https://www.imdb.com/title/tt8585800/?ref_=ttls_li_i", "Page_Title": "Control (Video Game 2019) - IMDb", "Number of Critics": "8", "Age Rating": "M", "Release Year": "2019"}
{"Url": "https://www.imdb.com/title/tt8585800/?ref_=ttls_li_tt", "Page_Title": "Control (Video Game 2019) - IMDb", "Number of Critics": "8", "Age Rating": "M", "Release Year": "2019"}
{"Url": "https://www.imdb.com/title/tt1319708/?ref_=ttls_li_i", "Page_Title": "Deus Ex: Human Revolution (Video Game 2011) - IMDb", "Number of Critics": "3", "Age Rating": "M", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt1319708/?ref_=ttls_li_tt", "Page_Title": "Deus Ex: Human Revolution (Video Game 2011) - IMDb", "Number of Critics": "3", "Age Rating": "M", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt1073668/?ref_=ttls_li_i", "Page_Title": "Mass Effect (Video Game 2007) - IMDb", "Number of Critics": "4", "Age Rating": "M", "Release Year": "2007"}
{"Url": "https://www.imdb.com/title/tt1073668/?ref_=ttls_li_tt", "Page_Title": "Mass Effect (Video Game 2007) - IMDb", "Number of Critics": "4", "Age Rating": "M", "Release Year": "2007"}
{"Url": "https://www.imdb.com/title/tt1267296/?ref_=ttls_li_i", "Page_Title": "Dead Space (Video Game 2008) - IMDb", "Number of Critics": "3", "Age Rating": "M", "Release Year": "2008"}
{"Url": "https://www.imdb.com/title/tt1267296/?ref_=ttls_li_tt", "Page_Title": "Dead Space (Video Game 2008) - IMDb", "Number of Critics": "3", "Age Rating": "M", "Release Year": "2008"}
{"Url": "https://www.imdb.com/title/tt3980364/?ref_=ttls_li_i", "Page_Title": "Inside (Video Game 2016) - IMDb", "Number of Critics": "5", "Age Rating": "M", "Release Year": "2016"}
{"Url": "https://www.imdb.com/title/tt3980364/?ref_=ttls_li_tt", "Page_Title": "Inside (Video Game 2016) - IMDb", "Number of Critics": "5", "Age Rating": "M", "Release Year": "2016"}
{"Url": "https://www.imdb.com/title/tt0433458/?ref_=ttls_li_i", "Page_Title": "Star Wars: Knights of the Old Republic II - The Sith Lords (Video Game 2004) - IMDb", "Number of Critics": "2", "Age Rating": "T", "Release Year": "2004"}
{"Url": "https://www.imdb.com/title/tt0433458/?ref_=ttls_li_tt", "Page_Title": "Star Wars: Knights of the Old Republic II - The Sith Lords (Video Game 2004) - IMDb", "Number of Critics": "2", "Age Rating": "T", "Release Year": "2004"}
{"Url": "https://www.imdb.com/title/tt1839558/?ref_=ttls_li_i", "Page_Title": "Mass Effect 3 (Video Game 2012) - IMDb", "Number of Critics": "7", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt1839558/?ref_=ttls_li_tt", "Page_Title": "Mass Effect 3 (Video Game 2012) - IMDb", "Number of Critics": "7", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt0177822/?ref_=ttls_li_i", "Page_Title": "Grim Fandango (Video Game 1998) - IMDb", "Number of Critics": "8", "Age Rating": "T", "Release Year": "1998"}
{"Url": "https://www.imdb.com/title/tt0177822/?ref_=ttls_li_tt", "Page_Title": "Grim Fandango (Video Game 1998) - IMDb", "Number of Critics": "8", "Age Rating": "T", "Release Year": "1998"}
{"Url": "https://www.imdb.com/title/tt1698007/?ref_=ttls_li_i", "Page_Title": "Super Mario Galaxy 2 (Video Game 2010) - IMDb", "Number of Critics": "1", "Age Rating": "E", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt1698007/?ref_=ttls_li_tt", "Page_Title": "Super Mario Galaxy 2 (Video Game 2010) - IMDb", "Number of Critics": "1", "Age Rating": "E", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt3540564/?ref_=ttls_li_i", "Page_Title": "Hotline Miami 2: Wrong Number (Video Game 2015) - IMDb", "Number of Critics": "3", "Age Rating": "M", "Release Year": "2015"}
{"Url": "https://www.imdb.com/title/tt3540564/?ref_=ttls_li_tt", "Page_Title": "Hotline Miami 2: Wrong Number (Video Game 2015) - IMDb", "Number of Critics": "3", "Age Rating": "M", "Release Year": "2015"}
{"Url": "https://www.imdb.com/title/tt0390163/?ref_=ttls_li_i", "Page_Title": "Kingdom Hearts II (Video Game 2005) - IMDb", "Number of Critics": "1", "Age Rating": "E10+", "Release Year": "2005"}
{"Url": "https://www.imdb.com/title/tt0390163/?ref_=ttls_li_tt", "Page_Title": "Kingdom Hearts II (Video Game 2005) - IMDb", "Number of Critics": "1", "Age Rating": "E10+", "Release Year": "2005"}
{"Url": "https://www.imdb.com/title/tt0286585/?ref_=ttls_li_i", "Page_Title": "Deus Ex (Video Game 2000) - IMDb", "Number of Critics": "0", "Age Rating": "M", "Release Year": "2000"}
{"Url": "https://www.imdb.com/title/tt0286585/?ref_=ttls_li_tt", "Page_Title": "Deus Ex (Video Game 2000) - IMDb", "Number of Critics": "0", "Age Rating": "M", "Release Year": "2000"}
{"Url": "https://www.imdb.com/title/tt0365498/?ref_=ttls_li_i", "Page_Title": "Metal Gear Solid 3: Snake Eater (Video Game 2004) - IMDb", "Number of Critics": "8", "Age Rating": "M", "Release Year": "2004"}
{"Url": "https://www.imdb.com/title/tt0365498/?ref_=ttls_li_tt", "Page_Title": "Metal Gear Solid 3: Snake Eater (Video Game 2004) - IMDb", "Number of Critics": "8", "Age Rating": "M", "Release Year": "2004"}
{"Url": "https://www.imdb.com/title/tt3390964/?ref_=ttls_li_i", "Page_Title": "The Walking Dead: Season Two (Video Game 2013) - IMDb", "Number of Critics": "14", "Age Rating": "M", "Release Year": "2013"}
{"Url": "https://www.imdb.com/title/tt3390964/?ref_=ttls_li_tt", "Page_Title": "The Walking Dead: Season Two (Video Game 2013) - IMDb", "Number of Critics": "14", "Age Rating": "M", "Release Year": "2013"}
{"Url": "https://www.imdb.com/title/tt0183066/?ref_=ttls_li_i", "Page_Title": "Fallout 2: A Post-Nuclear Role-Playing Game (Video Game 1998) - IMDb", "Number of Critics": "0", "Age Rating": "M", "Release Year": "1998"}
{"Url": "https://www.imdb.com/title/tt0183066/?ref_=ttls_li_tt", "Page_Title": "Fallout 2: A Post-Nuclear Role-Playing Game (Video Game 1998) - IMDb", "Number of Critics": "0", "Age Rating": "M", "Release Year": "1998"}
{"Url": "https://www.imdb.com/title/tt3763912/?ref_=ttls_li_i", "Page_Title": "Dragon Age: Inquisition (Video Game 2014) - IMDb", "Number of Critics": "10", "Age Rating": "M", "Release Year": "2014"}
{"Url": "https://www.imdb.com/title/tt3763912/?ref_=ttls_li_tt", "Page_Title": "Dragon Age: Inquisition (Video Game 2014) - IMDb", "Number of Critics": "10", "Age Rating": "M", "Release Year": "2014"}
{"Url": "https://www.imdb.com/title/tt3983144/?ref_=ttls_li_i", "Page_Title": "Yakuza 0 (Video Game 2015) - IMDb", "Number of Critics": "6", "Age Rating": "M", "Release Year": "2015"}
{"Url": "https://www.imdb.com/title/tt3983144/?ref_=ttls_li_tt", "Page_Title": "Yakuza 0 (Video Game 2015) - IMDb", "Number of Critics": "6", "Age Rating": "M", "Release Year": "2015"}
{"Url": "https://www.imdb.com/title/tt0438550/?ref_=ttls_li_i", "Page_Title": "Vampire: The Masquerade - Bloodlines (Video Game 2004) - IMDb", "Number of Critics": "1", "Age Rating": "M", "Release Year": "2004"}
{"Url": "https://www.imdb.com/title/tt0438550/?ref_=ttls_li_tt", "Page_Title": "Vampire: The Masquerade - Bloodlines (Video Game 2004) - IMDb", "Number of Critics": "1", "Age Rating": "M", "Release Year": "2004"}
{"Url": "https://www.imdb.com/title/tt1506437/?ref_=ttls_li_i", "Page_Title": "BioShock 2 (Video Game 2010) - IMDb", "Number of Critics": "11", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt1506437/?ref_=ttls_li_tt", "Page_Title": "BioShock 2 (Video Game 2010) - IMDb", "Number of Critics": "11", "Age Rating": "M", "Release Year": "2010"}
{"Url": "https://www.imdb.com/title/tt0244783/?ref_=ttls_li_i", "Page_Title": "The Secret of Monkey Island (Video Game 1990) - IMDb", "Number of Critics": "1", "Age Rating": "E", "Release Year": "1990"}
{"Url": "https://www.imdb.com/title/tt0244783/?ref_=ttls_li_tt", "Page_Title": "The Secret of Monkey Island (Video Game 1990) - IMDb", "Number of Critics": "1", "Age Rating": "E", "Release Year": "1990"}
{"Url": "https://www.imdb.com/title/tt0462423/?ref_=ttls_li_i", "Page_Title": "Metal Gear Solid 4: Guns of the Patriots (Video Game 2008) - IMDb", "Number of Critics": "1", "Age Rating": "M", "Release Year": "2008"}
{"Url": "https://www.imdb.com/title/tt0462423/?ref_=ttls_li_tt", "Page_Title": "Metal Gear Solid 4: Guns of the Patriots (Video Game 2008) - IMDb", "Number of Critics": "1", "Age Rating": "M", "Release Year": "2008"}
{"Url": "https://www.imdb.com/title/tt1797530/?ref_=ttls_li_i", "Page_Title": "Tomb Raider (Video Game 2013) - IMDb", "Number of Critics": "30", "Age Rating": "M", "Release Year": "2013"}
{"Url": "https://www.imdb.com/title/tt1797530/?ref_=ttls_li_tt", "Page_Title": "Tomb Raider (Video Game 2013) - IMDb", "Number of Critics": "30", "Age Rating": "M", "Release Year": "2013"}
{"Url": "https://www.imdb.com/title/tt2452050/?ref_=ttls_li_i", "Page_Title": "XCOM: Enemy Unknown (Video Game 2012) - IMDb", "Number of Critics": "2", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt2452050/?ref_=ttls_li_tt", "Page_Title": "XCOM: Enemy Unknown (Video Game 2012) - IMDb", "Number of Critics": "2", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt2015348/?ref_=ttls_li_i", "Page_Title": "Dark Souls (Video Game 2011) - IMDb", "Number of Critics": "6", "Age Rating": "M", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt2015348/?ref_=ttls_li_tt", "Page_Title": "Dark Souls (Video Game 2011) - IMDb", "Number of Critics": "6", "Age Rating": "M", "Release Year": "2011"}
{"Url": "https://www.imdb.com/title/tt3186880/?ref_=ttls_li_i", "Page_Title": "The Wolf Among Us (Video Game 2013) - IMDb", "Number of Critics": "15", "Age Rating": "M", "Release Year": "2013"}
{"Url": "https://www.imdb.com/title/tt3186880/?ref_=ttls_li_tt", "Page_Title": "The Wolf Among Us (Video Game 2013) - IMDb", "Number of Critics": "15", "Age Rating": "M", "Release Year": "2013"}
{"Url": "https://www.imdb.com/title/tt0853117/?ref_=ttls_li_i", "Page_Title": "Half-Life 2: Episode Two (Video Game 2007) - IMDb", "Number of Critics": "1", "Age Rating": "M", "Release Year": "2007"}
{"Url": "https://www.imdb.com/title/tt0853117/?ref_=ttls_li_tt", "Page_Title": "Half-Life 2: Episode Two (Video Game 2007) - IMDb", "Number of Critics": "1", "Age Rating": "M", "Release Year": "2007"}
{"Url": "https://www.imdb.com/title/tt5807780/?ref_=ttls_li_i", "Page_Title": "Spider-Man (Video Game 2018) - IMDb", "Number of Critics": "13", "Age Rating": "T", "Release Year": "2018"}
{"Url": "https://www.imdb.com/title/tt5807780/?ref_=ttls_li_tt", "Page_Title": "Spider-Man (Video Game 2018) - IMDb", "Number of Critics": "13", "Age Rating": "T", "Release Year": "2018"}
{"Url": "https://www.imdb.com/title/tt0879874/?ref_=ttls_li_i", "Page_Title": "Super Mario Galaxy (Video Game 2007) - IMDb", "Number of Critics": "5", "Age Rating": "E", "Release Year": "2007"}
{"Url": "https://www.imdb.com/title/tt0879874/?ref_=ttls_li_tt", "Page_Title": "Super Mario Galaxy (Video Game 2007) - IMDb", "Number of Critics": "5", "Age Rating": "E", "Release Year": "2007"}
{"Url": "https://www.imdb.com/title/tt4779924/?ref_=ttls_li_i", "Page_Title": "Cuphead: Don't Deal with the Devil (Video Game 2017) - IMDb", "Number of Critics": "7", "Age Rating": "E", "Release Year": "2017"}
{"Url": "https://www.imdb.com/title/tt4779924/?ref_=ttls_li_tt", "Page_Title": "Cuphead: Don't Deal with the Devil (Video Game 2017) - IMDb", "Number of Critics": "7", "Age Rating": "E", "Release Year": "2017"}
{"Url": "https://www.imdb.com/title/tt2370518/?ref_=ttls_li_i", "Page_Title": "Metal Gear Solid V: The Phantom Pain (Video Game 2015) - IMDb", "Number of Critics": "11", "Age Rating": "M", "Release Year": "2015"}
{"Url": "https://www.imdb.com/title/tt2370518/?ref_=ttls_li_tt", "Page_Title": "Metal Gear Solid V: The Phantom Pain (Video Game 2015) - IMDb", "Number of Critics": "11", "Age Rating": "M", "Release Year": "2015"}
{"Url": "https://www.imdb.com/title/tt2385021/?ref_=ttls_li_i", "Page_Title": "Borderlands 2 (Video Game 2012) - IMDb", "Number of Critics": "6", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt2385021/?ref_=ttls_li_tt", "Page_Title": "Borderlands 2 (Video Game 2012) - IMDb", "Number of Critics": "6", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt2322244/?ref_=ttls_li_i", "Page_Title": "Dishonored (Video Game 2012) - IMDb", "Number of Critics": "4", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt2322244/?ref_=ttls_li_tt", "Page_Title": "Dishonored (Video Game 2012) - IMDb", "Number of Critics": "4", "Age Rating": "M", "Release Year": "2012"}
{"Url": "https://www.imdb.com/title/tt1430111/?ref_=ttls_li_i", "Page_Title": "Ratchet & Clank Future: A Crack in Time (Video Game 2009) - IMDb", "Number of Critics": "0", "Age Rating": "E10+", "Release Year": "2009"}
{"Url": "https://www.imdb.com/title/tt1430111/?ref_=ttls_li_tt", "Page_Title": "Ratchet & Clank Future: A Crack in Time (Video Game 2009) - IMDb", "Number of Critics": "0", "Age Rating": "E10+", "Release Year": "2009"}
{"Url": "https://www.imdb.com/title/tt0309654/?ref_=ttls_li_i", "Page_Title": "Halo: Combat Evolved (Video Game 2001) - IMDb", "Number of Critics": "9", "Age Rating": "M", "Release Year": "2001"}
{"Url": "https://www.imdb.com/title/tt0309654/?ref_=ttls_li_tt", "Page_Title": "Halo: Combat Evolved (Video Game 2001) - IMDb", "Number of Critics": "9", "Age Rating": "M", "Release Year": "2001"}
{"Url": "https://www.imdb.com/title/tt0433623/?ref_=ttls_li_i", "Page_Title": "Ratchet & Clank: Up Your Arsenal (Video Game 2004) - IMDb", "Number of Critics": "2", "Age Rating": "T", "Release Year": "2004"}
{"Url": "https://www.imdb.com/title/tt0433623/?ref_=ttls_li_tt", "Page_Title": "Ratchet & Clank: Up Your Arsenal (Video Game 2004) - IMDb", "Number of Critics": "2", "Age Rating": "T", "Release Year": "2004"}
